# Generated by Django 3.1.3 on 2020-12-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0014_auto_20201221_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='仮登録'),
        ),
    ]
