# Generated by Django 3.1.3 on 2020-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0016_auto_20201223_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='仮登録'),
        ),
    ]
