# Generated by Django 3.1.3 on 2020-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0018_auto_20201223_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.BooleanField(blank=True, choices=[(1, 1)], default=0, null=True, verbose_name='仮登録'),
        ),
    ]
