# Generated by Django 3.1.3 on 2020-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0019_auto_20201223_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='仮登録'),
        ),
    ]
