# Generated by Django 3.1.3 on 2020-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0020_auto_20201223_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.BooleanField(default=False, verbose_name='仮登録'),
        ),
    ]
