# Generated by Django 3.1.3 on 2020-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0021_auto_20201223_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.BooleanField(verbose_name='仮登録'),
        ),
    ]
