# Generated by Django 3.1.3 on 2020-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0023_auto_20201224_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tmp',
            field=models.BooleanField(verbose_name='一時保存(本登録時はチェックを外してください)'),
        ),
    ]
